# Generated by Django 3.2.3 on 2021-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['year', 'tile_id', 'greenery_percentage', 'classified_by']},
        ),
        migrations.RemoveField(
            model_name='classification',
            name='contains_greenery',
        ),
        migrations.AddField(
            model_name='classification',
            name='greenery_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
