# Generated by Django 3.2.2 on 2021-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classification_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
