# Generated by Django 3.2.3 on 2021-06-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210607_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['year', 'tile', 'greenery_percentage', 'classified_by']},
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='tile_id',
            new_name='tile',
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('year', 'tile')},
        ),
    ]
